#%RAML 1.0
title: Retail Inventory System API
version: v2.0
baseUri: http://localhost:8081/api

uses:
  inventory: /exchange_modules/org.mule.templates/retail-inventory/1.0.1/retail_inventory.raml
  
traits:  
  productSearch: !include traits/productSearch.raml

types: 
  
  InventoryQueryResponse:
    properties:
      productId: 
        type: string
        description: Identifier of product
      variantId: 
        type: string
        description: Identifier of variant
      warehouses: inventory.WarehouseInventory[]
      
  InventoryReserveRequest:
    properties:
      productId:
        type: string
        description: Identifier of product
      variantId: 
        type: string
        description: Identifier of variant
      customerId: 
        type: string
        description: Identifier of customer
      quantity: 
        type: integer
        description: Count of product
      warehouseId: 
        type: string
        description: Identifier of warehouse
  
  MessageResponse:
    properties:
      message: string
      
/availability:
    get:
      displayName: Get availability
      description: Return product variant availability information for warehouses
      is: [ productSearch ]
      responses: 
        200:
          body: 
            application/json:
              type: InventoryQueryResponse
              example: !include examples/inventory-availability-response.yaml
/reservation:
    post:
      displayName: Create reservation
      description: Reservation of product in warehouse
      body: 
        application/json:
          type: InventoryReserveRequest
          example: !include examples/inventory-reserve-request.yaml
      responses: 
        201: 
          body: 
            application/json: 
              type: MessageResponse
              example: |
                {
                  "message": "Product was reserved" 
                }